### ISSUE TITLE
question on using double.c in batch in terminal??

### ISSUE THREAD

**Issue by xiao-wang007** [6by9/dcraw#3]
Hi, me again!

I'm really a noob on linux system. Please bear with me.
in the example you gave on doubling 640x200 to 640x400, it was just one single image. How do i do it in batch? like a few hundreds of .ppm to be doubled all at once.

Thank you!

**Comment by 6by9** [comment]
Example of doubling with dcraw?
I think you're referring to the [raspiraw app](https://github.com/6by9/raspiraw/blob/master/tools/double.c), in which case this is totally the wrong repo.

Simple bash scripting allows you to call the same exe for all files in the directory - Google and you'll find results such as https://stackoverflow.com/questions/10523415/bash-script-to-execute-command-on-all-files-in-a-directory#10523501
Otherwise you have the source code for double.c, so that could be altered as required.

**Comment by 6by9** [comment]
Closing as I don't believe this has anything to do with dcraw.
