### ISSUE TITLE
LibRaw has made a request

### ISSUE THREAD

**Issue by jdw1953** [6by9/dcraw#4]
https://github.com/LibRaw/LibRaw/issues/401

Latest comment on an issue started in LibRaw (see link above) has requested help in leveraging whatever information about Raspberry Pi camera (HQ 12Mp) raw already done here by done 6by9 into their coding. Anyone here up to the task in assistance? It would be a big step in getting this camera's raw format recognizable with more mainstream applications.

**Comment by LibRaw** [comment]
Sorry, this is not *our* request.

We completely dislike the 'new raw format for each new camera module' approach used by RPi team.

It it much better to change raspistill utility to record (standard, well documented, compatible with almost all raw processing apps) DNG format.

I guess, this request should be directed to RPi team from new camera module owners.

**Comment by 6by9** [comment]
There isn't a new raw format for each camera.

The JPEG+RAW format is legacy from Broadcom days when working with Android. Android had no way of requesting a raw (Bayer) image for debugging purposes and only allowed for a capture to deliver a JPEG. However almost all JPEG decoders will ignore extra data after the EOI tag, hence adding the raw image after the JPEG image. The debug tools knew where to look.

The raw data is literally the raw Bayer data received over the CSI-2 bus, including any CSI2 packing. The fact that IMX477 is a 12bit sensor means it uses the 12bit MIPI packing (2 pixels in 3 bytes) instead of the 10bit one (5 pixels in 4 bytes) used by OV5647 and IMX219.
If a 14bit sensor ever got added it would use the 14bit MIPI packing (4 pixels in 7 bytes).
Looking at the libraw source you've already copied the header parsing and different pixel format handling in.

The only thing that has been added to dcraw with each new sensor is the offsets from the end of file. Those are dictated by the size of the raw image for each mode.
They aren't strictly needed as you could just search from the start for the 0xffd9 EOI tag, and check for ```@BRCM``` immediately afterwards. That search is a bit tedious, hence most parsers using defined offsets from the end. Just watch for the EOI at the end of the thumbnail image to avoid a false positive.

Libcamera will produce DNGs for you, and is the route we're pursuing in future.

**Comment by LibRaw** [comment]
In fact, your older code, imported in LibRaw ~year ago or so  does not handle new format. That's why we think this is new format.

If someone will re-import your code (with respect to our approach to borrowed code) to LibRaw, we will accept the change. 
It is unlikely that we will be doing this ourselves anytime soon.

Summary: we didn't ask for help (as mentioned in original request :)

**Comment by 6by9** [comment]
The existing code explicitly looks for the EXIF name being ```RP_imx``` (and assumes IMX219), ```RP_OV```, or ```ov5647```, and then looks at the appropriate hard coded offsets for those models.
With a new sensor that has a new name and different offsets, it's not unsurprising that it fails to find the right information (hence https://github.com/6by9/dcraw/commit/951a43bf365ee758c8e687da5b6badc009891276 adding the offsets for IMX477 in this repo)

https://github.com/6by9/LibRaw/commit/ef5b7061d1f7b7b27144d93c002e5dc13ddf8701 does the long winded search through the file for the relevant EOI and ```@BRCM``` tag, so it should do the right thing on any Pi JPEG+raw. I will say I've only tested it against a single IMX477 image that I had lying around though. It could do with a bit more testing before considering merging.

(I'm quite tempted to amend the dcraw parsing in this branch to match this - saves having to make further changes there)

**Comment by LibRaw** [comment]
This patch reads  file byte by byte, right? I'll refuse it.

**Comment by 6by9** [comment]
> This patch reads file byte by byte, right? I'll refuse it.

Yes, it reads byte by byte until it finds the header, basically skipping over the JPEG (a couple of MB).
What's your specific objection? The OS will generally cache the file for you so it won't be painfully slow.

Another choice for a generic solution is to mmap the file and use memmem to find it. Happier? TBH mmap'ng the file would make a lot of operations nicer, but may make cross-platform support trickier.

Or mess around with a larger buffer with memmem, and then have to deal with the potential for the ID straddles the boundary of your loads, so 
```
unsigned char *found = NULL; 
fread( buffer size )

do 
{
   found = memmem(buffer, buffer_size, "\xFF\xD9@BRCM", 7);
   if (found)
   {
      // Mess with found to be able to move the file pointer back to the start of the header.
      break;
   }
   memcpy(buffer, &buffer[buffer_size - 7], 7);
   read_size = fread(&buffer[7], buffer_size-7, 1);
} while (read_size)
```
Do-able, but not as readable.

Or you add the offsets for each new sensor as they come out (it's not a new file format).

**Comment by LibRaw** [comment]
Reading full file, either byte-by-byte or entire file into buffer, will result in unacceptable metadata parsing speed.

It is acceptable (and unavoidable) for RAW decoding, but not for metadata parsing step.

**Comment by 6by9** [comment]
As already written, it is skipping the JPEG part of the file only, which would generally be 1-2MB of a ~20MB file for 12MPix raw 12. It does NOT read the whole file unless it isn't actually a Pi JPEG+RAW file (false positive on the EXIF name).

If that is unacceptable to you then your only option is adding the table of offsets for each mode, and you will have to add a new table for each sensor that is released (it's not a new file format).

You're already fairly certain that it's a Pi capture as it has checked the EXIF name, so it's not going to affect any other type of raw file.
Perhaps have the table of offsets, and if that fails but the EXIF name starts RP_ then you start doing the generic search. It's a choice between slow, or not working until updated.

**Comment by LibRaw** [comment]
In the only sample from this new camera I have on hands right now, @BRCM section has offset 0x5898D7 or slightly less than 6MB.

Imagine average today connection to NAS via WiFi at real 300Mbps or 37MB/sec transfer speed. In that (real) case, it is not possible to parse more than 6 files per second. Such speed is not acceptable if one want to query lot of files for metadata (e.g. to sort 1000s of files by EXIF shooting time, this is very real everyday scenario).

While improving LibRaw's metadata read speed last year, we've measured average amount of data being read on metadata parsing stage. Most files (this was a mix from many modern cameras) fits into 2-segment buffer 2x16kb (one for tags and one for external tables), this is big difference compared to ~6MB read.

That's why we're calling JPEG+RAW concatenated format 'ugly'. That's why we will not accept 'full jpeg section read' metadata parser into LibRaw. 

We continue to believe that user pressure to RPi team may result to switch to more acceptable format (DNG is preferred, of course)

**Comment by 6by9** [comment]
> That's why we're calling JPEG+RAW concatenated format 'ugly'. That's why we will not accept 'full jpeg section read' metadata parser into LibRaw.

I won't defend it as being nice, but it's the only solution that was available.

> We continue to believe that user pressure to RPi team may result to switch to more acceptable format (DNG is preferred, of course)

Sorry, it's just not going to happen with the raw files coming out of raspistill. We support libcamera, and have an equivalent app to raspistill for it, and that does support DNG.

raspistill deliberately has very low external dependencies, so having to add libtiff or similar to be able to write the DNG file isn't going to fly. It also doesn't hold the whole file in memory at one time (it's streamed from the GPU) so the issue of identifying the start of the ```@BRCM``` header exists there too, and switching from the MIPI CSI2 packing for raw data to the DNG version is also non-trivial.

Master branch of https://github.com/6by9/LibRaw updated to just add the offsets for IMX477. There's a second branch named generic with the search approach retained for info.

**Comment by LibRaw** [comment]
Thanks for the new offsets table.  This is the only way to go right now.

**Comment by 6by9** [comment]
No problem. Closing.
